-- SSHWeb 初始数据
USE `sshweb`;

-- 默认管理员账号 admin / admin123
INSERT IGNORE INTO `users` (`username`, `password_hash`, `role`, `status`) VALUES
('admin', '$2a$10$vYNOay//7iBS38PhrH9OuOCpGY6.KujwrMqttRVPU07ICl9BMw9hq', 'superadmin', 1);

-- 默认分组
INSERT IGNORE INTO `server_groups` (`name`, `sort_order`) VALUES
('生产环境', 1),
('测试环境', 2),
('开发环境', 3),
('数据库服务器', 4),
('Web服务器', 5),
('其他', 99);

-- 默认命令模板
INSERT IGNORE INTO `command_templates` (`name`, `category`, `command`, `description`, `is_dangerous`) VALUES
-- 1. 系统信息
('查看内核和系统信息', '系统信息', 'uname -a', '查看内核和系统信息', 0),
('查看Debian版本', '系统信息', 'cat /etc/debian_version', '查看 Debian 版本', 0),
('查看发行版信息', '系统信息', 'lsb_release -a', '查看发行版信息，可能需要安装 lsb-release', 0),
('查看主机名等信息', '系统信息', 'hostnamectl', '查看主机名、系统、内核等信息', 0),
('查看系统运行时间和负载', '系统信息', 'uptime', '查看系统运行时间和负载', 0),
('查看当前时间', '系统信息', 'date', '查看当前时间', 0),
('查看当前用户', '系统信息', 'whoami', '查看当前用户', 0),
('查看当前用户UID/GID', '系统信息', 'id', '查看当前用户 UID/GID', 0),
('查看系统版本', '系统信息', 'cat /etc/os-release', '查看操作系统版本信息', 0),
-- 2. 文件和目录
('显示当前目录', '文件和目录', 'pwd', '显示当前目录', 0),
('列出文件', '文件和目录', 'ls', '列出文件', 0),
('列出文件(易读)', '文件和目录', 'ls -lh', '以易读格式显示文件大小', 0),
('列出所有文件(含隐藏)', '文件和目录', 'ls -la', '显示隐藏文件', 0),
('进入目录', '文件和目录', 'cd /path/to/dir', '进入指定目录', 0),
('回到用户家目录', '文件和目录', 'cd ~', '回到用户家目录', 0),
('返回上次目录', '文件和目录', 'cd -', '返回上一次所在目录', 0),
('创建目录', '文件和目录', 'mkdir test', '创建目录', 0),
('创建多级目录', '文件和目录', 'mkdir -p a/b/c', '创建多级目录', 0),
('创建空文件', '文件和目录', 'touch file.txt', '创建空文件', 0),
('复制文件', '文件和目录', 'cp a.txt b.txt', '复制文件', 0),
('复制目录', '文件和目录', 'cp -r dir1 dir2', '复制目录', 0),
('移动或重命名', '文件和目录', 'mv old new', '移动或重命名', 0),
('删除文件', '文件和目录', 'rm file.txt', '删除文件', 0),
('删除目录', '文件和目录', 'rm -r dir', '删除目录', 0),
('强制删除目录', '文件和目录', 'rm -rf dir', '强制删除目录，谨慎使用', 1),
-- 3. 查看文件内容
('查看整个文件', '查看文件内容', 'cat file.txt', '查看整个文件', 0),
('分页查看文件', '查看文件内容', 'less file.txt', '分页查看', 0),
('查看前10行', '查看文件内容', 'head file.txt', '查看前 10 行', 0),
('查看前20行', '查看文件内容', 'head -n 20 file.txt', '查看前 20 行', 0),
('查看后10行', '查看文件内容', 'tail file.txt', '查看后 10 行', 0),
('查看后50行', '查看文件内容', 'tail -n 50 file.txt', '查看后 50 行', 0),
('实时查看日志', '查看文件内容', 'tail -f /var/log/syslog', '实时查看日志', 0),
-- 4. 查找文件和内容
('按文件名查找', '查找文件和内容', 'find / -name "file.txt" 2>/dev/null', '按文件名查找', 0),
('查找log文件', '查找文件和内容', 'find /var/log -type f -name "*.log"', '查找 log 文件', 0),
('在文件中搜索关键字', '查找文件和内容', 'grep "error" file.txt', '在文件中搜索关键字', 0),
('递归搜索目录', '查找文件和内容', 'grep -r "error" /var/log', '递归搜索目录', 0),
('忽略大小写搜索', '查找文件和内容', 'grep -i "error" file.txt', '忽略大小写', 0),
('搜索并显示行号', '查找文件和内容', 'grep -n "error" file.txt', '显示行号', 0),
-- 5. 软件包管理 apt
('更新软件源索引', '软件包管理', 'sudo apt update', '更新软件源索引', 0),
('升级已安装软件包', '软件包管理', 'sudo apt upgrade -y', '升级已安装软件包', 0),
('完整系统升级', '软件包管理', 'sudo apt full-upgrade -y', '更完整的系统升级', 0),
('安装软件', '软件包管理', 'sudo apt install nginx -y', '安装软件', 0),
('卸载软件(保留配置)', '软件包管理', 'sudo apt remove nginx', '卸载软件，保留配置', 0),
('卸载软件(删除配置)', '软件包管理', 'sudo apt purge nginx', '卸载软件并删除配置', 0),
('删除不需要的依赖', '软件包管理', 'sudo apt autoremove -y', '删除不再需要的依赖', 0),
('清理软件包缓存', '软件包管理', 'sudo apt clean', '清理软件包缓存', 0),
('搜索软件包', '软件包管理', 'apt search nginx', '搜索软件包', 0),
('查看软件包信息', '软件包管理', 'apt show nginx', '查看软件包信息', 0),
('查看已安装软件包', '软件包管理', 'apt list --installed', '查看已安装软件包', 0),
('查看已安装软件包(dpkg)', '软件包管理', 'dpkg -l', '查看已安装软件包', 0),
('查看软件安装文件列表', '软件包管理', 'dpkg -L nginx', '查看软件安装了哪些文件', 0),
-- 6. 服务管理 systemctl
('启动服务', '服务管理', 'sudo systemctl start nginx', '启动服务', 0),
('停止服务', '服务管理', 'sudo systemctl stop nginx', '停止服务', 0),
('重启服务', '服务管理', 'sudo systemctl restart nginx', '重启服务', 0),
('重新加载配置', '服务管理', 'sudo systemctl reload nginx', '重新加载配置', 0),
('查看服务状态', '服务管理', 'sudo systemctl status nginx', '查看服务状态', 0),
('设置开机自启', '服务管理', 'sudo systemctl enable nginx', '设置开机自启', 0),
('取消开机自启', '服务管理', 'sudo systemctl disable nginx', '取消开机自启', 0),
('查看所有服务', '服务管理', 'systemctl list-units --type=service', '查看服务列表', 0),
('查看启动失败的服务', '服务管理', 'systemctl --failed', '查看启动失败的服务', 0),
-- 7. 进程管理
('查看所有进程', '进程管理', 'ps aux', '查看所有进程', 0),
('查找某个进程', '进程管理', 'ps aux | grep nginx', '查找某个进程', 0),
('实时查看进程', '进程管理', 'top', '实时查看进程', 0),
('查看进程PID', '进程管理', 'pidof nginx', '查看进程 PID', 0),
('结束指定进程', '进程管理', 'kill PID', '结束指定进程', 0),
('强制结束进程', '进程管理', 'kill -9 PID', '强制结束进程', 1),
('按进程名结束', '进程管理', 'pkill nginx', '按进程名结束', 1),
-- 8. 网络相关
('查看IP地址', '网络', 'ip addr', '查看 IP 地址', 0),
('查看IP地址(简写)', '网络', 'ip a', '查看 IP 地址', 0),
('查看路由', '网络', 'ip route', '查看路由', 0),
('测试网络连通性', '网络', 'ping -c 4 8.8.8.8', '测试网络连通性', 0),
('测试DNS和网络', '网络', 'ping -c 4 google.com', '测试 DNS 和网络', 0),
('查看监听端口', '网络', 'ss -tulnp', '查看所有监听端口', 0),
('查看TCP/UDP连接', '网络', 'ss -tunap', '查看 TCP/UDP 连接', 0),
('查看公网IP', '网络', 'curl ifconfig.me', '查看公网 IP', 0),
('下载文件(wget)', '网络', 'wget URL', '下载文件', 0),
('请求网址内容', '网络', 'curl URL', '请求网址内容', 0),
-- 9. 防火墙 ufw
('查看防火墙状态', '防火墙', 'sudo ufw status', '查看防火墙状态', 0),
('启用防火墙', '防火墙', 'sudo ufw enable', '启用防火墙', 0),
('禁用防火墙', '防火墙', 'sudo ufw disable', '禁用防火墙', 0),
('放行SSH端口', '防火墙', 'sudo ufw allow 22', '放行 SSH', 0),
('放行HTTP端口', '防火墙', 'sudo ufw allow 80', '放行 HTTP', 0),
('放行HTTPS端口', '防火墙', 'sudo ufw allow 443', '放行 HTTPS', 0),
('禁止端口访问', '防火墙', 'sudo ufw deny 3306', '禁止 MySQL 端口', 0),
('删除防火墙规则', '防火墙', 'sudo ufw delete allow 80', '删除规则', 0),
-- 10. 磁盘和空间
('查看磁盘空间', '磁盘和空间', 'df -h', '查看磁盘空间', 0),
('查看当前目录各文件大小', '磁盘和空间', 'du -sh *', '查看当前目录下各文件/目录大小', 0),
('查看指定目录大小', '磁盘和空间', 'du -sh /var/log', '查看指定目录大小', 0),
('查看磁盘和分区', '磁盘和空间', 'lsblk', '查看磁盘和分区', 0),
('查看分区UUID', '磁盘和空间', 'blkid', '查看分区 UUID', 0),
('查看挂载信息', '磁盘和空间', 'mount', '查看挂载信息', 0),
('查看内存使用', '磁盘和空间', 'free -h', '查看内存使用情况', 0),
-- 11. 用户和权限
('查看当前登录用户', '用户和权限', 'who', '查看当前登录用户', 0),
('查看登录用户和操作', '用户和权限', 'w', '查看登录用户和操作', 0),
('添加用户', '用户和权限', 'adduser username', '添加用户', 0),
('修改用户密码', '用户和权限', 'passwd username', '修改用户密码', 0),
('删除用户', '用户和权限', 'deluser username', '删除用户', 0),
('将用户加入sudo组', '用户和权限', 'usermod -aG sudo username', '将用户加入 sudo 组', 0),
('查看用户所属组', '用户和权限', 'groups username', '查看用户所属组', 0),
('修改文件权限(数字)', '用户和权限', 'chmod 755 file.sh', '修改权限', 0),
('添加执行权限', '用户和权限', 'chmod +x file.sh', '添加执行权限', 0),
('修改文件所有者', '用户和权限', 'chown user:user file', '修改文件所有者', 0),
-- 12. 压缩和解压
('打包gzip压缩', '压缩和解压', 'tar -czvf file.tar.gz dir/', '打包并 gzip 压缩', 0),
('解压tar.gz', '压缩和解压', 'tar -xzvf file.tar.gz', '解压 tar.gz', 0),
('打包bzip2压缩', '压缩和解压', 'tar -cjvf file.tar.bz2 dir/', '打包并 bzip2 压缩', 0),
('解压tar.bz2', '压缩和解压', 'tar -xjvf file.tar.bz2', '解压 tar.bz2', 0),
('zip压缩', '压缩和解压', 'zip -r file.zip dir/', 'zip 压缩', 0),
('解压zip', '压缩和解压', 'unzip file.zip', '解压 zip', 0),
-- 13. 日志查看
('查看systemd日志', '日志查看', 'journalctl', '查看 systemd 日志', 0),
('查看最近错误日志', '日志查看', 'journalctl -xe', '查看最近错误日志', 0),
('查看nginx服务日志', '日志查看', 'journalctl -u nginx', '查看 nginx 服务日志', 0),
('实时查看nginx日志', '日志查看', 'journalctl -u nginx -f', '实时查看 nginx 日志', 0),
('查看今天的日志', '日志查看', 'journalctl --since today', '查看今天的日志', 0),
('查看内核日志', '日志查看', 'dmesg', '查看内核日志', 0),
('查看内核日志(可读时间)', '日志查看', 'dmesg -T', '显示可读时间', 0),
('查看登录记录', '安全', 'last -n 20', '查看最近20条登录记录', 0),
('查看SSH日志', '安全', 'tail -n 100 /var/log/auth.log', '查看SSH认证日志', 0),
-- 14. Docker 常用命令
('查看运行中的容器', 'Docker', 'docker ps', '查看运行中的容器', 0),
('查看所有容器', 'Docker', 'docker ps -a', '查看所有容器', 0),
('查看镜像', 'Docker', 'docker images', '查看镜像', 0),
('查看容器日志', 'Docker', 'docker logs container_name', '查看容器日志', 0),
('实时查看容器日志', 'Docker', 'docker logs -f container_name', '实时查看容器日志', 0),
('启动容器', 'Docker', 'docker start container_name', '启动容器', 0),
('停止容器', 'Docker', 'docker stop container_name', '停止容器', 0),
('重启容器', 'Docker', 'docker restart container_name', '重启容器', 0),
('进入容器(bash)', 'Docker', 'docker exec -it container_name bash', '进入容器', 0),
('进入容器(sh)', 'Docker', 'docker exec -it container_name sh', '没有 bash 时用 sh', 0),
('删除容器', 'Docker', 'docker rm container_name', '删除容器', 0),
('删除镜像', 'Docker', 'docker rmi image_name', '删除镜像', 0),
('清理Docker无用资源', 'Docker', 'docker system prune -f', '清理无用资源', 1),
-- Docker Compose
('后台启动Compose', 'Docker Compose', 'docker compose up -d', '后台启动', 0),
('停止并删除容器(Compose)', 'Docker Compose', 'docker compose down', '停止并删除容器', 0),
('查看Compose服务状态', 'Docker Compose', 'docker compose ps', '查看服务状态', 0),
('查看Compose日志', 'Docker Compose', 'docker compose logs -f', '查看日志', 0),
('重启Compose服务', 'Docker Compose', 'docker compose restart', '重启服务', 0),
-- 15. 系统清理
('清理apt缓存', '系统清理', 'sudo apt autoremove -y && sudo apt clean', '清理 apt 缓存和不需要的依赖', 0);

-- 默认系统设置
INSERT IGNORE INTO `settings` (`setting_key`, `setting_value`, `description`) VALUES
('system_name', 'SSHWeb 服务器群控面板', '系统名称'),
('login_title', 'Linux 服务器群控管理系统', '登录页标题'),
('default_page_size', '20', '默认分页数量'),
('terminal_theme', 'dark', '终端主题'),
('terminal_font_size', '14', '终端字体大小'),
('ssh_connect_timeout', '10000', 'SSH连接超时(毫秒)'),
('command_exec_timeout', '60000', '命令执行超时(毫秒)'),
('server_check_interval', '180', '服务器状态检测间隔(秒)'),
('server_monitor_concurrency', '5', '服务器状态检测并发数'),
('login_fail_limit', '5', '登录失败次数限制'),
('login_lock_time', '300', '登录失败锁定时间(秒)'),
('jwt_expires_in', '7d', 'Token有效期'),
('enable_dangerous_block', 'true', '启用危险命令拦截'),
('dangerous_action', 'block', '危险命令处理方式: block|confirm'),
('record_terminal_log', 'false', '记录终端日志'),
('allow_batch_dangerous', 'false', '允许批量执行危险命令'),
('tg_enabled', 'false', '是否启用Telegram通知'),
('tg_bot_token', '', 'Telegram Bot Token'),
('tg_chat_id', '', 'Telegram Chat ID'),
('alert_enable_offline', 'true', '启用服务器离线告警'),
('alert_enable_cpu', 'true', '启用CPU使用率告警'),
('alert_enable_memory', 'true', '启用内存使用率告警'),
('alert_enable_disk', 'false', '启用磁盘使用率告警'),
('alert_cpu_threshold', '90', 'CPU使用率告警阈值百分比'),
('alert_memory_threshold', '90', '内存使用率告警阈值百分比'),
('alert_disk_threshold', '90', '磁盘使用率告警阈值百分比'),
('alert_enable_expiry', 'true', '启用服务器到期提醒'),
('alert_server_expiry_days', '2', '服务器到期提前提醒天数'),
('alert_repeat_hours', '12', '相同告警重复提醒间隔小时'),
('alert_template_offline', '', '服务器离线通知模板'),
('alert_template_cpu', '', 'CPU告警通知模板'),
('alert_template_memory', '', '内存告警通知模板'),
('alert_template_disk', '', '磁盘告警通知模板'),
('alert_template_expiry', '', '服务器即将到期通知模板'),
('alert_template_expired', '', '服务器已到期通知模板');
